package Vista;

import Modelo.Alumno;
import Modelo.Materia;
import java.util.ArrayList;
import javax.swing.JInternalFrame;

/**
 * @author Grupo 15 Luis Ezequiel Sosa Lucas Saidman Luca Rodrigaño Ignacio
 * Rodriguez
*
 */

public class App extends javax.swing.JFrame {

    private ArrayList<Alumno> ALUMNOS = new ArrayList<>();
    private ArrayList<Materia> MATERIAS = new ArrayList<>();

    private JInternalFrame vistaAlumno;
    private JInternalFrame vistaMateria;
    private JInternalFrame vistaInscripcion;
    private JInternalFrame vistaInscriptos;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jmb_menu = new javax.swing.JMenuBar();
        jm_alumno = new javax.swing.JMenu();
        jmi_agregar_alumno = new javax.swing.JMenuItem();
        jm_materia = new javax.swing.JMenu();
        jmi_agregar_materia = new javax.swing.JMenuItem();
        jm_registro = new javax.swing.JMenu();
        jmi_inscripcion_materias = new javax.swing.JMenuItem();
        jmi_lista = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenu();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jm_alumno.setText("Alumno");

        jmi_agregar_alumno.setText("Agregar Alumno");
        jmi_agregar_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregar_alumnoActionPerformed(evt);
            }
        });
        jm_alumno.add(jmi_agregar_alumno);

        jmb_menu.add(jm_alumno);

        jm_materia.setText("Materia");

        jmi_agregar_materia.setText("Agregar Materia");
        jmi_agregar_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregar_materiaActionPerformed(evt);
            }
        });
        jm_materia.add(jmi_agregar_materia);

        jmb_menu.add(jm_materia);

        jm_registro.setText("Registro");

        jmi_inscripcion_materias.setText("Inscripcion a Materias");
        jmi_inscripcion_materias.setToolTipText("");
        jmi_inscripcion_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_inscripcion_materiasActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_inscripcion_materias);

        jmi_lista.setText("Lista");
        jmi_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listaActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_lista);

        jmb_menu.add(jm_registro);

        jm_salir.setText("Salir");

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jm_salir.add(jmi_salir);

        jmb_menu.add(jm_salir);

        setJMenuBar(jmb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_agregar_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregar_alumnoActionPerformed
       
                                                
    VistaAlumno vistaAlu = new VistaAlumno();
    Escritorio.add(vistaAlu);
    vistaAlu.setVisible(true);

    }//GEN-LAST:event_jmi_agregar_alumnoActionPerformed

    private void jmi_agregar_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregar_materiaActionPerformed

    VistaMaterias vistaMat = new VistaMaterias();
    Escritorio.add(vistaMat);
    vistaMat.setVisible(true);
    
    }//GEN-LAST:event_jmi_agregar_materiaActionPerformed

    private void jmi_inscripcion_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_inscripcion_materiasActionPerformed
        
    }//GEN-LAST:event_jmi_inscripcion_materiasActionPerformed

    private void jmi_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listaActionPerformed
        
    }//GEN-LAST:event_jmi_listaActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jmi_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jm_alumno;
    private javax.swing.JMenu jm_materia;
    private javax.swing.JMenu jm_registro;
    private javax.swing.JMenu jm_salir;
    private javax.swing.JMenuBar jmb_menu;
    private javax.swing.JMenuItem jmi_agregar_alumno;
    private javax.swing.JMenuItem jmi_agregar_materia;
    private javax.swing.JMenuItem jmi_inscripcion_materias;
    private javax.swing.JMenuItem jmi_lista;
    private javax.swing.JMenuItem jmi_salir;
    // End of variables declaration//GEN-END:variables
}
