
package Vista;

import Controladores.Alumno;
import Controladores.Materia;
import Modelo.Alumno;
import Modelo.Materia;
import java.util.Set;
import javax.swing.*;

/** 
    @author Grupo 6 
    Luis Ezequiel Sosa
    Lucas Saidman
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class VistaInscripcion extends javax.swing.JInternalFrame {

   
    
    /**
     * Creates new form VistaInscripcion
     */
    public VistaInscripcion(Set<Alumno> alumnos, Set<Materia> materias) {
        
    }
    
    private void configurarRenderers() {
       
    }

    private void cargarCombos() {
       
    }
    
    private Alumno buscarAlumnoPorLegajo(int legajo){
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_inscripcion = new javax.swing.JPanel();
        jl_titulo = new javax.swing.JLabel();
        jl_materia = new javax.swing.JLabel();
        jl_alumno = new javax.swing.JLabel();
        btn_inscribir = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        cb_materia = new javax.swing.JComboBox<>();
        cb_alumno = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jl_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Formulario de Inscripción");

        jl_materia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_materia.setText("Elija una materia");

        jl_alumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_alumno.setText("Elija un Alumno");

        btn_inscribir.setText("Inscribir");
        btn_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribirActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        cb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_materia.setSelectedIndex(-1);
        cb_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_materiaActionPerformed(evt);
            }
        });

        cb_alumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_alumno.setSelectedIndex(-1);
        cb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_alumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_inscripcionLayout = new javax.swing.GroupLayout(jp_inscripcion);
        jp_inscripcion.setLayout(jp_inscripcionLayout);
        jp_inscripcionLayout.setHorizontalGroup(
            jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_inscripcionLayout.createSequentialGroup()
                .addGroup(jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_inscripcionLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btn_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_inscripcionLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)))
                .addGroup(jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174))
        );
        jp_inscripcionLayout.setVerticalGroup(
            jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_inscripcionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jl_titulo)
                .addGap(45, 45, 45)
                .addGroup(jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jp_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_inscripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_inscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribirActionPerformed
      
    }//GEN-LAST:event_btn_inscribirActionPerformed

    private void cb_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_materiaActionPerformed

    private void cb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_alumnoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inscribir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cb_alumno;
    private javax.swing.JComboBox<String> cb_materia;
    private javax.swing.JLabel jl_alumno;
    private javax.swing.JLabel jl_materia;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JPanel jp_inscripcion;
    // End of variables declaration//GEN-END:variables
}
